# src/conclave/infrastructure/universal/presets.py
"""Preset-Registry — Vordefinierte Provider-Konfigurationen.

Jedes Preset enthaelt alle Felder die der UniversalAdapter braucht.
"custom" ist das leere Preset fuer beliebige Endpoints.
"""

from __future__ import annotations

PRESETS: dict[str, dict] = {
    "openai": {
        "name": "openai",
        "label": "OpenAI (Chat Completions)",
        "description": "Kompatibler Chat-Completions-Pfad fuer GPT-Modelle.",
        "api_key_env": "OPENAI_API_KEY",
        "requires_api_key": True,
        "api_url": "https://api.openai.com/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": ["gpt-5.6", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.1"],
    },
    "openai-responses": {
        "name": "openai-responses",
        "label": "OpenAI (Responses API)",
        "description": "Empfohlener OpenAI-Pfad fuer moderne Reasoning- und Agentenmodelle.",
        "api_key_env": "OPENAI_API_KEY",
        "requires_api_key": True,
        "recommended": True,
        "api_url": "https://api.openai.com/v1/responses",
        "response_path": "output_text",
        "message_format": "openai-responses",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "input_tokens",
        "usage_output_key": "output_tokens",
        "models": ["gpt-5.6", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.1"],
    },
    "anthropic": {
        "name": "anthropic",
        "label": "Anthropic (Claude)",
        "description": "Claude-Modelle fuer Schreiben, Coding, Review und komplexe Analyse.",
        "api_key_env": "ANTHROPIC_API_KEY",
        "requires_api_key": True,
        "recommended": True,
        "api_url": "https://api.anthropic.com/v1/messages",
        "response_path": "content[0].text",
        "message_format": "standard",
        "auth_format": "x-api-key",
        "usage_path": "usage",
        "usage_input_key": "input_tokens",
        "usage_output_key": "output_tokens",
        "models": ["claude-sonnet-5", "claude-opus-5", "claude-sonnet-4-6", "claude-haiku-4-5"],
    },
    "ollama": {
        "name": "ollama",
        "label": "Ollama (Lokal)",
        "description": "Lokale Modelle ohne API-Key ueber den Ollama-Server.",
        "requires_api_key": False,
        "recommended": True,
        "api_url": "http://localhost:11434/api/chat",
        "response_path": "message.content",
        "message_format": "standard",
        "auth_format": "none",
        "usage_path": "",
        "usage_input_key": "prompt_eval_count",
        "usage_output_key": "eval_count",
        "models": ["llama3.3", "llama3.2", "mistral", "codellama", "gemma2", "phi3"],
    },
    "gemini": {
        "name": "gemini",
        "label": "Google Gemini",
        "description": "Gemini GenerateContent fuer schnelle multimodale und agentische Aufgaben.",
        "api_key_env": "GEMINI_API_KEY",
        "requires_api_key": True,
        "api_url": "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        "response_path": "candidates[0].content.parts[0].text",
        "message_format": "gemini",
        "auth_format": "query",
        "usage_path": "usageMetadata",
        "usage_input_key": "promptTokenCount",
        "usage_output_key": "candidatesTokenCount",
        "models": ["gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.1-pro-preview"],
    },
    "mistral": {
        "name": "mistral",
        "label": "Mistral AI",
        "description": "Mistral Chat-Completions-kompatible API.",
        "api_key_env": "MISTRAL_API_KEY",
        "requires_api_key": True,
        "api_url": "https://api.mistral.ai/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": ["mistral-medium-2508", "mistral-small-2506", "magistral-medium-2509", "devstral-2512"],
    },
    "openai-no-thinking": {
        "name": "openai-no-thinking",
        "label": "OpenAI (Chat Completions, Thinking disabled)",
        "description": "OpenAI-kompatible Endpunkte mit explizit deaktiviertem Thinking-Parameter.",
        "api_key_env": "OPENAI_API_KEY",
        "requires_api_key": True,
        "api_url": "https://api.openai.com/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": [],
        "extra_body": {"disable_thinking": True},
    },
    "qwen-dashscope": {
        "name": "qwen-dashscope",
        "label": "Qwen via DashScope (Singapore, Thinking off)",
        "description": "Qwen-Modelle ueber DashScope im OpenAI-kompatiblen Modus.",
        "requires_api_key": True,
        "api_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": ["qwen-plus", "qwen-max", "qwen-turbo"],
        "extra_body": {"enable_thinking": False},
        "api_key_env": "DASHSCOPE_API_KEY",
    },
    "qwen-dashscope-thinking": {
        "name": "qwen-dashscope-thinking",
        "label": "Qwen via DashScope (Singapore, Thinking on, QwQ)",
        "description": "Qwen mit aktiviertem Reasoning ueber DashScope.",
        "requires_api_key": True,
        "api_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": ["qwen-plus"],
        "extra_body": {"enable_thinking": True},
        "api_key_env": "DASHSCOPE_API_KEY",
        "extracts_reasoning": True,
    },
    "deepseek": {
        "name": "deepseek",
        "label": "DeepSeek (offizielle API)",
        "description": "DeepSeek Chat und Reasoner ueber die offizielle Chat-Completions-API.",
        "requires_api_key": True,
        "api_url": "https://api.deepseek.com/v1/chat/completions",
        "response_path": "choices[0].message.content",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": ["deepseek-chat", "deepseek-reasoner"],
        "api_key_env": "DEEPSEEK_API_KEY",
        "extracts_reasoning": True,
    },
    "custom": {
        "name": "custom",
        "label": "Custom (Manuell)",
        "description": "Manueller Provider fuer OpenAI-kompatible oder eigene JSON-Endpunkte.",
        "requires_api_key": False,
        "api_url": "",
        "response_path": "",
        "message_format": "standard",
        "auth_format": "bearer",
        "usage_path": "usage",
        "usage_input_key": "prompt_tokens",
        "usage_output_key": "completion_tokens",
        "models": [],
    },
}


def get_preset(name: str) -> dict | None:
    """Gibt ein Preset zurueck oder None."""
    return PRESETS.get(name)


def list_presets() -> list[dict]:
    """Alle Presets als Liste."""
    return list(PRESETS.values())
